{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"success"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.swift.ArgumentParser\/documentation\/ArgumentParser\/ExitCode","preciseIdentifier":"s:14ArgumentParser8ExitCodeV","text":"ExitCode"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/argumentparser\/exitcode\/success"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.swift.ArgumentParser\/documentation\/ArgumentParser\/ExitCode\/success","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An exit code that indicates successful completion of a command."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"success"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ExitCode","preciseIdentifier":"s:14ArgumentParser8ExitCodeV"}],"title":"success","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"s:14ArgumentParser8ExitCodeV7successACvpZ","modules":[{"name":"ArgumentParser"}]},"hierarchy":{"paths":[["doc:\/\/org.swift.ArgumentParser\/documentation\/ArgumentParser","doc:\/\/org.swift.ArgumentParser\/documentation\/ArgumentParser\/ExitCode"]]},"references":{"doc://org.swift.ArgumentParser/documentation/ArgumentParser":{"role":"collection","title":"ArgumentParser","abstract":[{"type":"text","text":"Straightforward, type-safe argument parsing for Swift."}],"identifier":"doc:\/\/org.swift.ArgumentParser\/documentation\/ArgumentParser","kind":"symbol","type":"topic","url":"\/documentation\/argumentparser"},"doc://org.swift.ArgumentParser/documentation/ArgumentParser/ExitCode/success":{"role":"symbol","title":"success","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"success"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ExitCode","preciseIdentifier":"s:14ArgumentParser8ExitCodeV"}],"abstract":[{"type":"text","text":"An exit code that indicates successful completion of a command."}],"identifier":"doc:\/\/org.swift.ArgumentParser\/documentation\/ArgumentParser\/ExitCode\/success","kind":"symbol","type":"topic","url":"\/documentation\/argumentparser\/exitcode\/success"},"doc://org.swift.ArgumentParser/documentation/ArgumentParser/ExitCode":{"role":"symbol","title":"ExitCode","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ExitCode"}],"abstract":[{"type":"text","text":"An error type that only includes an exit code."}],"identifier":"doc:\/\/org.swift.ArgumentParser\/documentation\/ArgumentParser\/ExitCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ExitCode"}],"url":"\/documentation\/argumentparser\/exitcode"}}}